name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
      - name: Install Dependancies
        run: dotnet restore ./src/ZaNetDev.MassTransit.MessageHelpers.CodeEnumeration/
      - name: Build
        run:  dotnet build src/ZaNetDev.MassTransit.MessageHelpers.CodeEnumeration/ZaNetDev.MassTransit.MessageHelpers.CodeEnumeration.csproj --configuration Release --no-restore
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/ZaNetDev.MassTransit.MessageHelpers.CodeEnumeration/ZaNetDev.MassTransit.MessageHelpers.CodeEnumeration.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          # INCLUDE_SYMBOLS: false
